name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug
labels: ["triage"]
body:
- type: checkboxes
  attributes:
    label: Is there an already existing issue for this?
    description: Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/GalaxyDreamWings/World/issues?q=is%3Aissue%20sort%3Acreated-desc).
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.

      If relevant, add a minimal example so that we can reproduce the error by running the code. It is very important for the snippet to be as succinct (minimal) as possible, so please take time to trim down any irrelevant code to help us debug efficiently.
      Your example should be fully self-contained and not rely on any artifact that should be downloaded.
      For example:

      ```python
      # All necessary imports at the beginning
      import torch

      # A succinct reproducing example trimmed down to the essential parts:
      t = torch.rand(5, 10)  # Note: the bug is here, we should pass requires_grad=True
      t.sum().backward()
      ```

      If the code is too long (hopefully, it isn't), feel free to put it in a public gist and link it in the issue: https://gist.github.com.

      Please also paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full** traceback of the exception. It may be relevant to wrap error messages in ```` ```triple quotes blocks``` ````.
      If your issue is related to numerical accuracy or reproducibility, please read the [numerical accuracy](https://docs.pytorch.org/docs/stable/notes/numerical_accuracy.html) and [reproducibility](https://docs.pytorch.org/docs/stable/notes/randomness.html) notes. If the difference is not expected as described in these documents, please provide appropriate justification on why one result is wrong and the other is correct.
    placeholder: |
      A clear and concise description of what the bug is.

      ```python
      # Sample code to reproduce the problem
      ```

      ```
      The error message you got, with the full traceback.
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: Versions
    description: |
      Please run the following and paste the output below.
      ```sh
      wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
      # For security purposes, please check the contents of collect_env.py before running it.
      python collect_env.py
      ```
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: A concise description of what is expected to happen. Please include references, if applicable, to the Fast DDS documentation/DDS specification where the expected behavior is established.
  validations:
    required: true
- type: textarea
  id: current-behavior
  attributes:
    label: Current behavior
    description: A concise description of what is currently happening.
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: Steps to reproduce
    description: Please provide an unambigous set of steps to reproduce the issue. If relevant, include a minimal example.
  validations:
    required: true
- type: textarea
  id: fast-dds-version
  attributes:
    label: Fast DDS version/commit
    description: Please provide the release tag, branch, commit hash...
  validations:
    required: true
- type: dropdown
  id: platforms
  attributes:
    label: Platform/Architecture
    description: Tier 1 platforms/architectures where the issue is reproducible. If not a Tier 1 platform, consider opening the issue in the proper discussion forum (check contributing guidelines)
    multiple: true
    options:
      - Ubuntu Focal 20.04 amd64
      - Ubuntu Focal 20.04 arm64
      - Windows 10 Visual Studio 2019
      - MacOS Mojave 10.14
      - Other. Please specify in Additional context section.
  validations:
    required: true
- type: dropdown
  id: transport
  attributes:
    label: Transport layer
    description: Transport layer with which the issue is reproducible.
    multiple: true
    options:
      - Default configuration, UDPv4 & SHM
      - UDPv4
      - UDPv6
      - TCPv4
      - TCPv6
      - Shared Memory Transport (SHM)
      - Intra-process
      - Data-sharing delivery
      - Zero copy
  validations:
    required: true
- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: Please provide any additional information that can be of interest such as network interfaces being used, ROS 2 version if applicable, etc.
  validations:
    required: false
- type: textarea
  id: xml-profiles
  attributes:
    label: XML configuration file
    description: Please copy and paste the XML configuration file being used if applicable. This will be automatically formatted into code, so no need for backquotes.
    render: xml
  validations:
    required: false
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backquotes.
    render: shell
  validations:
    required: false
- type: textarea
  id: network-traffic
  attributes:
    label: Network traffic capture
    description: If applicable, please provide with a network traffic capture of the relevant packages (for example using Wireshark). Use this box to comment on the capture if needed.
  validations:
    required: false
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
